name: Test

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          package-manager-cache: false
      - run: npm ci
      - run: npm run test:e2e
